Improved protobuf
cloud-custodian/cel-python pull request #23
Opened 2021-04-08 18:46 UTC by slott56

Warning: massive change

1. Improve some protobuf handling in general. This introduces better name handling so that a single name can have a be combination of type and value references. Names start with type associations. Some names also get values.

2. Fix the conversion of test cases from protobuf text to Gherkin.

2021-04-08 19:52 UTC, slott56 commented
Closes #17 and #3.

2021-04-09 20:13 UTC, kylejohnson514 commented on src/celpy/c7nlib.py
> +                        "Resource": celpy.json_to_cel(resource),
Need to update these `Resource`, `Now`, and `Event` fields throughout the codebase to be `resource`, `now`, and `event`

2021-04-09 20:14 UTC, kylejohnson514 requested changes
Capitalization of the `Resource`, `Now`, and `Event` fields needs to be pulled in from master, but once those are resolved, the rest of this PR LGTM!

2021-04-14 13:16 UTC, kylejohnson514 approved these changes
LGTM, I tested this locally with some CEL expressions in Custodian as well

2021-04-15 22:51 UTC, merged